/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 11:55:10 GMT 2018
 */

package server;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import server.ServerMain;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServerMain_ESTest extends ServerMain_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServerMain.main((String[]) null);
      ServerMain.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServerMain serverMain0 = new ServerMain();
  }
}
