/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 11:53:30 GMT 2018
 */

package chat;

import org.junit.Test;
import static org.junit.Assert.*;
import chat.Chat;
import chat.User;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Chat_ESTest extends Chat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Chat chat0 = new Chat();
      ArrayList<User> arrayList0 = chat0.getUsers();
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Chat chat0 = new Chat();
      chat0.addUser((User) null);
      ArrayList<User> arrayList0 = chat0.getUsers();
      assertFalse(arrayList0.isEmpty());
  }
}
