/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 01 11:54:30 GMT 2018
 */

package plugins;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import plugins.Power;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Power_ESTest extends Power_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Power power0 = new Power(2308, 2308);
      Double double0 = power0.call();
      assertEquals(Double.POSITIVE_INFINITY, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Power power0 = new Power((-1), (-1));
      Double double0 = power0.call();
      assertEquals((-1.0), (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Power power0 = new Power((-4963), (-4963));
      Double double0 = power0.call();
      assertEquals(-0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Power power0 = new Power(0, 0);
      Double double0 = power0.call();
      assertEquals(1.0, (double)double0, 0.01);
  }
}
